# flexoki, horizon-dark, meliora, tender, wombat
import = [
    "~/.config/alacritty/themes/themes/meliora.toml",
    "~/.config/alacritty/meliora.toml",
    "~/meliora.toml",
    "~/.alacritty.meliora.toml",
]

live_config_reload = true

[window]
decorations = "Full"
blur = true
opacity = 0.9
padding = { x = 8, y = 0 }
dynamic_padding = false
decorations_theme_variant = "Dark"
dimensions = { columns = 110, lines = 26 }

[font]
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }
size = 12
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[colors.footer_bar]
background = '#c1b090'